name: code-nerf
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.11.0
  - torchvision
  - cudatoolkit=11.3
  - imageio
  - tensorboard
  - matplotlib
  - pyyaml
  - rich
  - pip
  - pip:
      - hydra-core
      - hydra-colorlog

