name: code-nerf
channels:
  - pytorch-lts
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.8.2
  - torchvision
  - cudatoolkit=11.1
  - imageio
  - tensorboard
  - matplotlib
  - pyyaml
