defaults:
  - datamodule: carla_cars
  - model: generative_film_nerf
  - optim: adam
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

distributed: True
checkpoint_dir: ~
gpus: ~
dist_url: "env://"
cudnn_benchmark: True
data_dir: ${oc.env:DATA_DIR}

num_rays: ${oc.decode:${oc.env:NUM_RAYS}}
scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.99995

experiment:
  randomseed: 1
  logdir: ${oc.env:LOG_DIR}
  id: "carla128-film-sirendecoder-overfit1object-1e-5-5e-3-2condlayers"
  encoder_lr: 1e-5
  decoder_lr: 1e-3
  iterations: 5000
  validation_freq: 50000000
  save_freq: 500

