experiment:
    id: srn-cars-test1
    logdir: logs
    randomseed: 42
    iterations: 100000
    validate_every: 500
    save_every: 5000
    print_every: 100

dataset:
    type: SRNDataset
    basedir: /home/tkhurana/Documents/akash/datasets/srn/srn_cars
    image_size: 128
    world_scale: 1.0
    train_batch_size: 2
    val_batch_size: 1
    near: 0.8
    far: 1.8

models:
    coarse:
        type: FlexibleNeRFModel
        num_layers: 8
        hidden_size: 256
        skip_connect_ids: [4]
    fine:
        type: FlexibleNeRFModel
        num_layers: 8
        hidden_size: 256
        skip_connect_ids: [4]

optimizer:
    type: Adam
    lr: 5.0E-5
    scheduler_gamma: 0.1
    scheduler_step_size: 500000

nerf:
    ray_sampler:
        num_random_rays: 8192
    point_sampler:
        num_coarse: 64
        num_fine: 128
        near_limit: 0.8
        far_limit: 1.8
        spacing_mode: "lindepth"
        perturb: True
    embedder:
        num_encoding_fn_xyz: 10
        include_input_xyz: True
        log_sampling_xyz: True
        use_viewdirs: True
        num_encoding_fn_dir: 4
        include_input_dir: True
        log_sampling_dir: True
    white_background: False
    train:
        chunksize: 4096
        radiance_field_noise_std: 0.05
    validation:
        chunksize: 8192
        radiance_field_noise_std: 0.05
