_target_: src.datamodules.carla_datamodule.CARLADataModule
train_batch_size: 1
val_batch_size: 1
data_dir: ${data_dir} # data_dir is specified in config.yaml
num_workers: 0
pin_memory: True
shuffle: True
